/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pages;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;

/**
 *
 * @author dagi
 */
public class pengeluaran extends javax.swing.JPanel {

    /**
     * Creates new form pengeluaran
     */
    
    public void clear(){
    textArea1.setText(" ");
    txt_modal.setText(" ");
        
   
    }
    
        String Tanggal;
    public pengeluaran() {
        initComponents();
        Date date = new Date();
        SimpleDateFormat tanggal = new SimpleDateFormat("dd-MM-yyyy");
        
        txt_tgl.setText(tanggal.format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pn_pengeluaran = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelRound1 = new panelCustom.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        txt_tgl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_modal = new textfield.TextField();
        jLabel10 = new javax.swing.JLabel();
        btnsave = new swing.Button();
        textAreaScroll2 = new textarea.TextAreaScroll();
        textArea1 = new textarea.TextArea();

        setLayout(new java.awt.CardLayout());

        mainPanel.setPreferredSize(new java.awt.Dimension(1670, 814));
        mainPanel.setLayout(new java.awt.CardLayout());

        pn_pengeluaran.setBackground(new java.awt.Color(166, 104, 68));
        pn_pengeluaran.setPreferredSize(new java.awt.Dimension(1670, 920));
        pn_pengeluaran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel1.setText("Pengeluaran");
        pn_pengeluaran.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 13, 225, 61));

        panelRound1.setBackground(new java.awt.Color(235, 180, 136));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Tanggal      :");
        panelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 29, -1, -1));

        txt_tgl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_tgl.setText("Tanggal ");
        panelRound1.add(txt_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 29, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Pengeluaran :");
        panelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 61, 109, -1));
        panelRound1.add(txt_modal, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 61, 240, 52));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Keterangan  :");
        panelRound1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 148, 109, -1));

        btnsave.setBackground(new java.awt.Color(166, 104, 68));
        btnsave.setText("Simpan");
        btnsave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        panelRound1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 362, 108, 37));

        textArea1.setColumns(20);
        textArea1.setRows(5);
        textAreaScroll2.setViewportView(textArea1);

        panelRound1.add(textAreaScroll2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 240, 185));

        pn_pengeluaran.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 440, 630));

        mainPanel.add(pn_pengeluaran, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String tanggal = txt_tgl.getText();
        int Modal = Integer.parseInt(txt_modal.getText());
        String Keterangan = textArea1.getText();

        String simpantransaksi = "INSERT INTO belanja (tanggal,modal,keterangan) VALUES (?, ?, ?)";
        try {
            Connection c = Koneksi.getKoneksi();
            PreparedStatement statement = c.prepareStatement(simpantransaksi);
            statement.setString(1, tanggal);
            statement.setInt(2, Modal);
            statement.setString(3, Keterangan);
            statement.execute();

            JOptionPane.showMessageDialog(null, "Simpan Berhasil");

        } catch (Exception e) {
           JOptionPane. showMessageDialog(this, e);
        }
        clear();

    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    private panelCustom.PanelRound panelRound1;
    private javax.swing.JPanel pn_pengeluaran;
    private textarea.TextArea textArea1;
    private textarea.TextAreaScroll textAreaScroll2;
    private textfield.TextField txt_modal;
    private javax.swing.JLabel txt_tgl;
    // End of variables declaration//GEN-END:variables
}
