package PageForm;

import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dagi
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pn_datamaster = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pn_transaksi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pn_close = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pn_laporan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel2.setBackground(new java.awt.Color(89, 47, 37));

        pn_datamaster.setBackground(new java.awt.Color(89, 47, 37));
        pn_datamaster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_datamaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_datamasterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_datamasterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_datamasterMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pn_datamasterMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pn_datamasterMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icondashboard/master-data 1.png"))); // NOI18N
        jLabel1.setText("Data Master");

        javax.swing.GroupLayout pn_datamasterLayout = new javax.swing.GroupLayout(pn_datamaster);
        pn_datamaster.setLayout(pn_datamasterLayout);
        pn_datamasterLayout.setHorizontalGroup(
            pn_datamasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pn_datamasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_datamasterLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pn_datamasterLayout.setVerticalGroup(
            pn_datamasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
            .addGroup(pn_datamasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_datamasterLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel1)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        pn_transaksi.setBackground(new java.awt.Color(89, 47, 37));
        pn_transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_transaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_transaksiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pn_transaksiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pn_transaksiMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icondashboard/cash_transaction_icon_194057 1.png"))); // NOI18N
        jLabel2.setText("Transaksi");

        javax.swing.GroupLayout pn_transaksiLayout = new javax.swing.GroupLayout(pn_transaksi);
        pn_transaksi.setLayout(pn_transaksiLayout);
        pn_transaksiLayout.setHorizontalGroup(
            pn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_transaksiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pn_transaksiLayout.setVerticalGroup(
            pn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
            .addGroup(pn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_transaksiLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel2)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        pn_close.setBackground(new java.awt.Color(89, 47, 37));
        pn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_closeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pn_closeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pn_closeMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icondashboard/close-button 1.png"))); // NOI18N
        jLabel9.setText("Close");

        javax.swing.GroupLayout pn_closeLayout = new javax.swing.GroupLayout(pn_close);
        pn_close.setLayout(pn_closeLayout);
        pn_closeLayout.setHorizontalGroup(
            pn_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_closeLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel9)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        pn_closeLayout.setVerticalGroup(
            pn_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_closeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icondashboard/Group 3 (1).png"))); // NOI18N

        pn_laporan.setBackground(new java.awt.Color(89, 47, 37));
        pn_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_laporanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pn_laporanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pn_laporanMouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icondashboard/cash_transaction_icon_194057 1.png"))); // NOI18N
        jLabel5.setText("Laporan");

        javax.swing.GroupLayout pn_laporanLayout = new javax.swing.GroupLayout(pn_laporan);
        pn_laporan.setLayout(pn_laporanLayout);
        pn_laporanLayout.setHorizontalGroup(
            pn_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_laporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_laporanLayout.setVerticalGroup(
            pn_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_laporanLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_datamaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pn_transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_laporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(pn_datamaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        jPanel3.setBackground(new java.awt.Color(140, 74, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icondashboard/Group 2 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(523, 523, 523)
                .addComponent(jLabel4)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel4)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pn_datamasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_datamasterMouseClicked
      //datta master di klik  
        DataMaster dm=new DataMaster();
       dm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_pn_datamasterMouseClicked

    private void pn_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_transaksiMouseClicked
        //transaksi dikilik
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pn_transaksiMouseClicked

    private void pn_datamasterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_datamasterMouseEntered
        //data master di samper
        pn_datamaster.setBackground(new Color(81,69,55));
    }//GEN-LAST:event_pn_datamasterMouseEntered

    private void pn_datamasterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_datamasterMouseExited
       //datamaster ditinggal
         pn_datamaster.setBackground(new Color(119,107,93));
    }//GEN-LAST:event_pn_datamasterMouseExited

    private void pn_transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_transaksiMouseEntered
        //transaksi di samper
         pn_transaksi.setBackground(new Color(81,69,55));
    }//GEN-LAST:event_pn_transaksiMouseEntered

    private void pn_transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_transaksiMouseExited
        //transaksi di tinggal
        pn_transaksi.setBackground(new Color(119,107,93));
    }//GEN-LAST:event_pn_transaksiMouseExited

    private void pn_datamasterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_datamasterMousePressed
        // ditekan
        pn_datamaster.setBackground(new Color(157,145,131));
    }//GEN-LAST:event_pn_datamasterMousePressed

    private void pn_datamasterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_datamasterMouseReleased
        // tidak ditekan
        pn_datamaster.setBackground(new Color(119,107,93));
    }//GEN-LAST:event_pn_datamasterMouseReleased

    private void pn_transaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_transaksiMousePressed
        //ditekan
        pn_transaksi.setBackground(new Color(157,145,131));
    }//GEN-LAST:event_pn_transaksiMousePressed

    private void pn_transaksiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_transaksiMouseReleased
        // tidak ditekan
        pn_transaksi.setBackground(new Color(119,107,93));
    }//GEN-LAST:event_pn_transaksiMouseReleased

    private void pn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_closeMouseClicked
        // diklik
        this.dispose();
    }//GEN-LAST:event_pn_closeMouseClicked

    private void pn_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_closeMouseEntered
        // disamper
        pn_close.setBackground(new Color(81,69,55));
    }//GEN-LAST:event_pn_closeMouseEntered

    private void pn_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_closeMouseExited
        // ditinggal
        pn_close.setBackground(new Color(119,107,93));
    }//GEN-LAST:event_pn_closeMouseExited

    private void pn_closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_closeMousePressed
        // ditekan
       
        pn_close.setBackground(new Color(157,145,131));
    }//GEN-LAST:event_pn_closeMousePressed

    private void pn_closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_closeMouseReleased
        // tidak ditekan
        pn_close.setBackground(new Color(119,107,93));
    }//GEN-LAST:event_pn_closeMouseReleased

    private void pn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_laporanMouseClicked
        //transaksi dikilik
        Laporan lp=new Laporan();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pn_laporanMouseClicked

    private void pn_laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_laporanMouseEntered
        //transaksi di samper
        pn_laporan.setBackground(new Color(81,69,55));
    }//GEN-LAST:event_pn_laporanMouseEntered

    private void pn_laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_laporanMouseExited
        //transaksi di tinggal
        pn_laporan.setBackground(new Color(119,107,93));
    }//GEN-LAST:event_pn_laporanMouseExited

    private void pn_laporanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_laporanMousePressed
        //ditekan
        pn_laporan.setBackground(new Color(157,145,131));
    }//GEN-LAST:event_pn_laporanMousePressed

    private void pn_laporanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_laporanMouseReleased
        // tidak ditekan
        pn_laporan.setBackground(new Color(119,107,93));
    }//GEN-LAST:event_pn_laporanMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pn_close;
    private javax.swing.JPanel pn_datamaster;
    private javax.swing.JPanel pn_laporan;
    private javax.swing.JPanel pn_transaksi;
    // End of variables declaration//GEN-END:variables
}
